name: password_manager
description: "Password manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  localization: ^2.1.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  auto_injector: ^2.0.5
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - lib/assets/
